// Generated by CoffeeScript 1.7.1
module.exports = function(conf) {
  var applicationInfo, getStatus, gitInfo;
  gitInfo = (require('git-info'))();
  applicationInfo = {
    id: conf.name,
    version: conf.version,
    startupTime: new Date
  };
  getStatus = function() {
    return gitInfo.then(function(git) {
      return {
        snapshotTimestamp: new Date,
        applicationInfo: applicationInfo,
        git: git
      };
    });
  };
  return {
    install: function(server) {
      return server.controller('GET', '/status', getStatus);
    }
  };
};
