// Generated by CoffeeScript 1.7.1
var applicationInfo, conf, getStatus, gitInfo;

conf = require('./package.json');

gitInfo = (require('git-info'))();

applicationInfo = {
  id: conf.name,
  version: conf.version,
  startupTime: new Date
};

getStatus = function() {
  return gitInfo.then(function(git) {
    return {
      snapshotTimestamp: new Date,
      applicationInfo: applicationInfo,
      git: git
    };
  });
};

module.exports = {
  install: function(server) {
    return server.controller('GET', '/status', getStatus);
  }
};
